### ISSUE TITLE
Custom font isn't working

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-time-date#28]
**Presentation URL:**
Please make a copy if you are going to make changes 

https://apps.risevision.com/editor/workspace/c4a67d47-b809-4c23-880a-57694881a884/?cid=a9dbdcf0-00c2-45c6-aa6e-14933558ec46

http://preview.risevision.com/?type=presentation&id=c4a67d47-b809-4c23-880a-57694881a884&showui=false

**What is not working/What is currently happening:**
When you enter a custom font in the time and date widget it doesn't work in preview

Custom font: https://storage.googleapis.com/risemedialibrary-a9dbdcf0-00c2-45c6-aa6e-14933558ec46/Presentation%20Assets/Trade%20Gothic%20LT%20Bold.ttf

**What is expected to work/What is the client expecting:**
The time and date widget registers the custom font

**What has been tried so far:**
I tried clearing preview cache, reloading, when entering the custom font i've tried http and https

Let me know if you need anything else.

Thanks

**Comment by donnapep** [comment]
Fixed by #29.

**Comment by stulees** [comment]
@sheadarlison FYI, the fix #29  had to be rolled back as it broke the use of Google Fonts. I've reopened this issue and will investigate again.
