### ISSUE TITLE
seconds with clock

### ISSUE THREAD

**Issue by pbtesoroni** [Rise-Vision/widget-time-date#47]
Is it possible to include the seconds with the clock only widget?

**Comment by sheadarlison** [comment]
Hi @pbtesoroni, we have no plans to add seconds to the Time and Date Widget currently. 

One way you could show a clock with seconds on your display though is using the HTML Widget with a clock embed code, here's one example but there are a number of different options online: https://24timezones.com/clock-widget/digital

Thanks!
